# Generated by Django 4.2.7 on 2023-11-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_ukraine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('establishment_type', models.CharField(choices=[('HO', 'Hotel'), ('CA', 'Cafe'), ('RE', 'Restaurant')], default='HO', max_length=2)),
                ('capacity', models.IntegerField()),
                ('covid_hygiene', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='owner',
            field=models.BooleanField(default=False),
        ),
    ]
