# Generated by Django 4.2.7 on 2023-11-18 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_ukraine', '0002_establishment_user_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Establishment',
        ),
    ]
