# Generated by Django 4.2.7 on 2023-11-18 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_ukraine', '0003_delete_establishment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('establishment_type', models.CharField(choices=[('HO', 'Hotel'), ('CA', 'Cafe'), ('RE', 'Restaurant')], default='HO', max_length=2)),
                ('capacity', models.IntegerField()),
                ('covid_hygiene', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_ukraine.user')),
            ],
        ),
    ]
